name: umeng_analytics_with_push_platform_interface
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  pedantic: ^1.11.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0"